name: ghosttears
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bitsdojo_window: ^0.1.1+1
  cupertino_icons: ^1.0.2
  fluent_ui: ^3.9.1
  fluentui_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.0.0+1
  provider: ^6.0.2
  system_theme: ^1.0.1
  url_launcher: ^6.0.18
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
